/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import com.sun.tools.javac.Main;
import server.Message;
import java.awt.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author talha
 */
public class GoGame extends javax.swing.JFrame {

    public int player = 0;
    public int turn = 0;
    ArrayList<JLabel> listOfLabel = new ArrayList<>();
    int startX = 150;  // X-coordinate of the starting point
    int startY = 50;  // Y-coordinate of the starting point 50 - 710 y
    int endX = 870;   // X-coordinate of the ending point 150 870 x
    int endY = 710;   // Y-coordinate of the ending point

    public class boardComp extends JComponent {

        public boardComp() {
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g;
            g2d.setPaint(Color.RED);
            g2d.setStroke(new BasicStroke(5.f));
            for (int i = startY; i <= endY; i += 110) {
                g2d.drawLine(startX, i, endX, i);
            }
            for (int i = startX; i <= endX; i += 120) {
                g2d.drawLine(i, startY, i, endY);
            }
        }
    }

    public static GoGame goGame;
    String nickName;
    boardComp boardPaint;

    public GoGame() {
        initComponents();
        boardPaint = new boardComp();
        pnl_game.setLayout(new BorderLayout());
        pnl_game.add(boardPaint, BorderLayout.CENTER);
        goGame = this;

    }

    private class Clicklistener implements MouseListener {

        int moveIndex = 0;

        public void mouseClicked(MouseEvent e) {
            Object source = e.getSource();
            if (source instanceof JLabel && turn == 1) {

                JLabel clickedLabel = (JLabel) e.getSource();
                ImageIcon icon = null;
                if (player == 1) {
                    icon = new ImageIcon("src/images/black.png");
                } else if (player == 2) {
                    icon = new ImageIcon("src/images/white.png");
                }
                clickedLabel.setIcon(icon);
                int currentIndex = pnl_game.getComponentZOrder(clickedLabel);
                pnl_game.setComponentZOrder(clickedLabel, pnl_game.getComponentCount() - 1);
                pnl_game.repaint();
                moveIndex = listOfLabel.indexOf(clickedLabel);
                System.out.println(moveIndex);
                clickedLabel.getParent().setComponentZOrder(clickedLabel, 0);
                int columns = (endX - startX) / 120;
                int rows = (endY - startY) / 110;
                int index = 0;
                for (int i = 0; i <= rows; i++) {
                    for (int j = 0; j <= columns; j++) {
                        int x = j * 120 + startX - 15;
                        int y = i * 110 + startY - 15;
                        listOfLabel.get(index).setLocation(x, y);
                        index++;
                    }
                }
                turn = 0;
                Message msg = new Message(Message.Message_Type.Turn);
                msg.content = "p"; //play
                Client.Send(msg);
            }
        }

        @Override
        public void mousePressed(MouseEvent e
        ) {
        }

        @Override
        public void mouseReleased(MouseEvent e
        ) {
        }

        @Override
        public void mouseEntered(MouseEvent e
        ) {
        }

        @Override
        public void mouseExited(MouseEvent e
        ) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnl_main = new javax.swing.JPanel();
        pnl_settings = new javax.swing.JPanel();
        lbl_nickname = new javax.swing.JLabel();
        txtb_nickname = new javax.swing.JTextField();
        btn_play = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_chat = new javax.swing.JTextArea();
        lbl_chat = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        txtb_player1Name = new javax.swing.JTextField();
        txtb_player2Name = new javax.swing.JTextField();
        lbl_vs = new javax.swing.JLabel();
        lbl_gameName = new javax.swing.JLabel();
        txtb_sendMessage = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        lbl_turn = new javax.swing.JLabel();
        pnl_game = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 760));
        setMinimumSize(new java.awt.Dimension(1440, 760));
        setName("GameFrame"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnl_main.setBackground(new java.awt.Color(255, 204, 204));
        pnl_main.setMaximumSize(new java.awt.Dimension(1440, 760));
        pnl_main.setMinimumSize(new java.awt.Dimension(1440, 760));
        pnl_main.setPreferredSize(new java.awt.Dimension(1440, 760));
        pnl_main.setLayout(new java.awt.GridBagLayout());

        pnl_settings.setBackground(new java.awt.Color(0, 204, 204));
        pnl_settings.setMaximumSize(new java.awt.Dimension(120, 760));
        pnl_settings.setMinimumSize(new java.awt.Dimension(120, 760));

        lbl_nickname.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nickname.setText("Nickname");

        txtb_nickname.setMinimumSize(new java.awt.Dimension(65, 25));

        btn_play.setText("Play");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });

        txta_chat.setEditable(false);
        txta_chat.setColumns(20);
        txta_chat.setRows(5);
        jScrollPane1.setViewportView(txta_chat);

        lbl_chat.setForeground(new java.awt.Color(0, 0, 0));
        lbl_chat.setText("Chat");

        f.setEditable(false);

        txtb_player1Name.setEditable(false);

        txtb_player2Name.setEditable(false);
        txtb_player2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtb_player2NameActionPerformed(evt);
            }
        });

        lbl_vs.setForeground(new java.awt.Color(0, 0, 0));
        lbl_vs.setText("VS");

        lbl_gameName.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lbl_gameName.setForeground(new java.awt.Color(255, 51, 51));
        lbl_gameName.setText("GO GAME");

        txtb_sendMessage.setEditable(false);
        txtb_sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtb_sendMessageActionPerformed(evt);
            }
        });

        btn_send.setText("Send");
        btn_send.setEnabled(false);
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        lbl_turn.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnl_settingsLayout = new javax.swing.GroupLayout(pnl_settings);
        pnl_settings.setLayout(pnl_settingsLayout);
        pnl_settingsLayout.setHorizontalGroup(
            pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_settingsLayout.createSequentialGroup()
                .addGroup(pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_settingsLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lbl_gameName))
                    .addGroup(pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_settingsLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lbl_nickname)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtb_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_settingsLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_play, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnl_settingsLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(txtb_player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lbl_vs)
                            .addGap(18, 18, 18)
                            .addComponent(txtb_player2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_settingsLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lbl_chat))
                    .addGroup(pnl_settingsLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_settingsLayout.createSequentialGroup()
                                .addComponent(txtb_sendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_send))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_settingsLayout.createSequentialGroup()
                                .addComponent(lbl_turn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnl_settingsLayout.setVerticalGroup(
            pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_gameName)
                .addGap(28, 28, 28)
                .addGroup(pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtb_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nickname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_play)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtb_player2Name)
                    .addComponent(lbl_vs)
                    .addComponent(txtb_player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(lbl_turn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(lbl_chat)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtb_sendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_send))
                .addGap(204, 204, 204)
                .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 247;
        gridBagConstraints.ipady = 240;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnl_main.add(pnl_settings, gridBagConstraints);

        pnl_game.setBackground(new java.awt.Color(255, 204, 102));
        pnl_game.setMaximumSize(new java.awt.Dimension(99999, 99999));
        pnl_game.setMinimumSize(new java.awt.Dimension(1067, 1000));
        pnl_game.setPreferredSize(new java.awt.Dimension(1445, 1200));
        pnl_game.setSize(new java.awt.Dimension(1200, 1200));

        javax.swing.GroupLayout pnl_gameLayout = new javax.swing.GroupLayout(pnl_game);
        pnl_game.setLayout(pnl_gameLayout);
        pnl_gameLayout.setHorizontalGroup(
            pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1075, Short.MAX_VALUE)
        );
        pnl_gameLayout.setVerticalGroup(
            pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        pnl_main.add(pnl_game, gridBagConstraints);

        getContentPane().add(pnl_main);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:

        if (txtb_nickname.getText().equals("")) {
            txtb_nickname.setText("choose nickname");
        } else {
            btn_play.setEnabled(false);
            txtb_nickname.setEnabled(false);
            nickName = txtb_nickname.getText();
            txtb_player1Name.setText(nickName);

            // adding labels to the playable lines
            int labelX = 40, labelY = 40;
            int columns = (endX - startX) / 120;
            int rows = (endY - startY) / 110;

            Clicklistener click = new Clicklistener();
            for (int i = 0; i <= rows; i++) {
                for (int j = 0; j <= columns; j++) {
                    JLabel lbl = new JLabel();
                    listOfLabel.add(lbl);
                    lbl.addMouseListener(click);
                    int x = j * 120 + startX - 15;
                    int y = i * 110 + startY - 15;
                    ImageIcon icon = new ImageIcon("src/images/empty.png");
                    lbl.setIcon(icon);
                    pnl_game.add(lbl); // x = 150 - 870 = 120 ; y = 50 - 710 = 110

                    lbl.setBounds(x, y, labelX, labelY);

                }
            }

            // start client
            Client.Start("127.0.0.1", 2000);
        }
    }//GEN-LAST:event_btn_playActionPerformed

    private void txtb_player2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtb_player2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtb_player2NameActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Client.Stop();
    }//GEN-LAST:event_formWindowClosing

    private void txtb_sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtb_sendMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtb_sendMessageActionPerformed

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
        String msg = txtb_sendMessage.getText();
        String oldMsg = txta_chat.getText();
        String newMsg = oldMsg + nickName + ": " + msg + "\n";
        txta_chat.setText(newMsg);
        txtb_sendMessage.setText("");
        Message text = new Message(Message.Message_Type.Text);
        text.content = msg;
        Client.Send(text);
    }//GEN-LAST:event_btn_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GoGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_play;
    public javax.swing.JButton btn_send;
    public javax.swing.JTextField f;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_chat;
    private javax.swing.JLabel lbl_gameName;
    private javax.swing.JLabel lbl_nickname;
    private javax.swing.JLabel lbl_turn;
    private javax.swing.JLabel lbl_vs;
    private javax.swing.JPanel pnl_game;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JPanel pnl_settings;
    public javax.swing.JTextArea txta_chat;
    private javax.swing.JTextField txtb_nickname;
    private javax.swing.JTextField txtb_player1Name;
    public javax.swing.JTextField txtb_player2Name;
    public javax.swing.JTextField txtb_sendMessage;
    // End of variables declaration//GEN-END:variables
}
